# Generated by Django 6.0.6 on 2026-06-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillexam',
            name='questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('objective', 'Objective (Multiple Choice)'), ('subjective', 'Subjective (Text Answer)')], default='objective', max_length=20)),
                ('options', models.JSONField(blank=True, help_text="List of options for objective questions, e.g. ['Option A', 'Option B']", null=True)),
                ('correct_index', models.IntegerField(blank=True, help_text='0-based index of the correct option (for objective questions)', null=True)),
                ('model_answer', models.TextField(blank=True, help_text='Model answer for subjective questions')),
                ('weight', models.IntegerField(default=1, help_text='Marks for this question')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='verification.skillexam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
