# Generated by Django 6.0.6 on 2026-06-08 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_hours', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_offered', to='skills.teachableskill')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to=settings.AUTH_USER_MODEL)),
                ('request_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_requested', to='skills.learnableskill')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration_hours', models.IntegerField()),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('teacher_rating', models.IntegerField(blank=True, null=True)),
                ('learner_rating', models.IntegerField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('learner_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exchanges.exchangeproposal')),
                ('skill_taught', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_taught', to='skills.skill')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('teach_earn', 'Teach Earn'), ('learn_spend', 'Learn Spend'), ('signup_bonus', 'Signup Bonus'), ('referral_bonus', 'Referral Bonus'), ('feedback_reward', 'Feedback Reward'), ('verification_reward', 'Verification Reward')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchangesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
