# Generated by Django 6.0.6 on 2026-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('average_salary', models.CharField(blank=True, help_text='e.g., NPR 1,200,000 - 2,500,000 per year', max_length=100)),
                ('growth_outlook', models.CharField(blank=True, help_text='e.g., +25% YoY', max_length=100)),
                ('estimated_hours_per_skill', models.JSONField(blank=True, default=dict, help_text='Map skill_id or skill name -> estimated hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_skills', models.ManyToManyField(related_name='career_paths', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['title'],
            },
        ),
    ]
