# Generated by Django 6.0.6 on 2026-06-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('password_changed', 'Password Changed'), ('exchange_proposal', 'Exchange Proposal Received'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('session_scheduled', 'Session Scheduled'), ('session_reminder', 'Session Reminder'), ('session_completed', 'Session Completed'), ('skill_verified', 'Skill Verified'), ('credit_earned', 'Credit Earned'), ('credit_spent', 'Credit Spent'), ('certificate_uploaded', 'Certificate Uploaded'), ('welcome', 'Welcome'), ('message', 'Message')], max_length=30)),
                ('preferred_notification', models.CharField(blank=True, choices=[('exchange_proposal', 'Exchange Proposal'), ('proposal_accepted', 'Proposal Accepted'), ('proposal_rejected', 'Proposal Rejected'), ('session_scheduled', 'Session Scheduled'), ('session_reminder', 'Session Reminder'), ('credit_update', 'Credit Update')], max_length=30, null=True)),
                ('title', models.CharField(default='', max_length=200)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
